include:
  - ${HOME}/.aztec/docker-compose.sandbox.yml

services:
  setup-account:
    image: "aztecprotocol/aztec"
    restart: "no"
    depends_on:
      - aztec
    environment:
      PXE_URL: "http://aztec:8080"
      SECRET_KEY: "0x2490e659effed473b8900b6ffca8b2dfa0b50f3ee6493684477923b4dedbb275"
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo -n "Waiting for aztec sandbox to be ready..."
        while ! curl -s http://aztec:8080/status ; do
          sleep 1
          echo -n "."
        done
        echo "done"

        echo "Creating account..."
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js create-account --secret-key $$SECRET_KEY
  setup-contract:
    image: "aztecprotocol/aztec"
    restart: "no"
    depends_on:
      setup-account:
        condition: service_completed_successfully
    environment:
      PXE_URL: "http://aztec:8080"
      SECRET_KEY: "0x2490e659effed473b8900b6ffca8b2dfa0b50f3ee6493684477923b4dedbb275"
      ADDRESS: "0x0627c5a3c006c7cf2413042101281424c7fded01c285c5d834c3ca5fc855f52c"
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo "Deploying counter contract..."
        # CounterContract constructor: initialize(headstart: u64, owner: AztecAddress, outgoing_viewer: AztecAddress)
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js deploy -sk $$SECRET_KEY --salt 0x01 CounterContract --args 1 $$ADDRESS $$ADDRESS --init initialize

        echo; echo
        echo "Deploying token contract..."
        # TokenContract constructor: constructor(admin: AztecAddress, name: str<31>, symbol: str<31>, decimals: u8)
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js deploy -sk $$SECRET_KEY --salt 0x01 TokenContract --args $$ADDRESS "Test Token" "TST" 18
