include:
  - ${HOME}/.aztec/docker-compose.sandbox.yml

services:
  setup-account:
    image: "aztecprotocol/aztec"
    restart: "no"
    depends_on:
      - aztec
    environment:
      PXE_URL: "http://aztec:8080"
      SECRET_KEY: "0x2490e659effed473b8900b6ffca8b2dfa0b50f3ee6493684477923b4dedbb275"
    volumes:
      - ../src/lib/deployment-data:/deployment-data
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo -n "Waiting for aztec sandbox to be ready..."
        while ! curl -s http://aztec:8080/status ; do
          sleep 1
          echo -n "."
        done
        echo "done"

        echo "Creating account..."
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js create-account --secret-key $$SECRET_KEY --json > /deployment-data/account.json
        cat /deployment-data/account.json
  setup-contract:
    image: "aztecprotocol/aztec"
    restart: "no"
    depends_on:
      setup-account:
        condition: service_completed_successfully
    volumes:
      - ../src/lib/deployment-data:/deployment-data
    environment:
      PXE_URL: "http://aztec:8080"
    entrypoint:
      - /bin/bash
      - -c
      - |
        SECRET_KEY=$(cat /deployment-data/account.json | jq -r .secretKey)
        ADDRESS=$(cat /deployment-data/account.json | jq -r .address)
        echo "Using secret key: $$SECRET_KEY"
        echo "Using address: $$ADDRESS"
        echo
        echo "Deploying counter contract..."
        # CounterContract constructor: initialize(headstart: u64, owner: AztecAddress, outgoing_viewer: AztecAddress)
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js deploy -sk $$SECRET_KEY --salt 0x01 CounterContract --args 1 $$ADDRESS --init initialize --json > /deployment-data/counter.json
        cat /deployment-data/counter.json

        echo; echo
        echo "Deploying token contract..."
        # TokenContract constructor: constructor(admin: AztecAddress, name: str<31>, symbol: str<31>, decimals: u8)
        node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js deploy -sk $$SECRET_KEY --salt 0x01 TokenContract --args $$ADDRESS "Test Token" "TST" 18 --json > /deployment-data/token.json
        cat /deployment-data/token.json
